// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAim8zBn3_OWU5fAk6qtqmdVrCnjdHbaW4',
    appId: '1:561860638892:web:4311259b5fc0770dc5c709',
    messagingSenderId: '561860638892',
    projectId: 'skill-waves-49184',
    authDomain: 'skill-waves-49184.firebaseapp.com',
    storageBucket: 'skill-waves-49184.firebasestorage.app',
    measurementId: 'G-3TFP26D95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7P0CNq_H7J4R_I9SYEX50J1K146FzJcQ',
    appId: '1:561860638892:android:f8b359b1239557ccc5c709',
    messagingSenderId: '561860638892',
    projectId: 'skill-waves-49184',
    storageBucket: 'skill-waves-49184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ibeImA3cMoetwaKPC1sGIbmDP8zMcj8',
    appId: '1:561860638892:ios:cdaa8efff4f68a04c5c709',
    messagingSenderId: '561860638892',
    projectId: 'skill-waves-49184',
    storageBucket: 'skill-waves-49184.firebasestorage.app',
    iosClientId: '561860638892-f8r0h1qmrdtj14mnbs679ntl908l1670.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillWaves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ibeImA3cMoetwaKPC1sGIbmDP8zMcj8',
    appId: '1:561860638892:ios:cdaa8efff4f68a04c5c709',
    messagingSenderId: '561860638892',
    projectId: 'skill-waves-49184',
    storageBucket: 'skill-waves-49184.firebasestorage.app',
    iosClientId: '561860638892-f8r0h1qmrdtj14mnbs679ntl908l1670.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillWaves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAim8zBn3_OWU5fAk6qtqmdVrCnjdHbaW4',
    appId: '1:561860638892:web:2edccd6af405eb75c5c709',
    messagingSenderId: '561860638892',
    projectId: 'skill-waves-49184',
    authDomain: 'skill-waves-49184.firebaseapp.com',
    storageBucket: 'skill-waves-49184.firebasestorage.app',
    measurementId: 'G-KT4EH8MCRG',
  );
}
